// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXeLM7vmkd37T9-KAnUw13hVXQin3vaXY',
    appId: '1:7618526028:web:9092f9db1e0002eb11ede9',
    messagingSenderId: '7618526028',
    projectId: 'prenta-842a9',
    authDomain: 'prenta-842a9.firebaseapp.com',
    storageBucket: 'prenta-842a9.appspot.com',
    measurementId: 'G-ELWMRJPDBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2_q6ie5KZ3lXbsoDTAr4CaTRL19OfATg',
    appId: '1:7618526028:android:d6c33a2a7703d46811ede9',
    messagingSenderId: '7618526028',
    projectId: 'prenta-842a9',
    storageBucket: 'prenta-842a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz7T9hBOjwBjxNjmxkh40cOCTXrwIR9R4',
    appId: '1:7618526028:ios:71a10b04c76aebb911ede9',
    messagingSenderId: '7618526028',
    projectId: 'prenta-842a9',
    storageBucket: 'prenta-842a9.appspot.com',
    iosBundleId: 'com.example.printa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz7T9hBOjwBjxNjmxkh40cOCTXrwIR9R4',
    appId: '1:7618526028:ios:71a10b04c76aebb911ede9',
    messagingSenderId: '7618526028',
    projectId: 'prenta-842a9',
    storageBucket: 'prenta-842a9.appspot.com',
    iosBundleId: 'com.example.printa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXeLM7vmkd37T9-KAnUw13hVXQin3vaXY',
    appId: '1:7618526028:web:e901dbaad92b4f3111ede9',
    messagingSenderId: '7618526028',
    projectId: 'prenta-842a9',
    authDomain: 'prenta-842a9.firebaseapp.com',
    storageBucket: 'prenta-842a9.appspot.com',
    measurementId: 'G-M5M2XJGBFH',
  );
}
